### ISSUE TITLE
Where is the degrees per second defined?

### ISSUE THREAD

**Issue by zorrobyte** [lee-ck/Model-Predictive-Control#1]
I'm learning Acado MPC myself. Looking through your code, I see the hard constraints on absolute acceleration and steer angle:
https://github.com/lee-ck/Model-Predictive-Control/blob/master/MPC_carmodel/ACADO/ACADO_main_.m#L107

But I'm having a hard time finding where these are constrained:
<img width="264" alt="image" src="https://user-images.githubusercontent.com/7257172/64450330-e6b53400-d0af-11e9-989b-ebdf897721f2.png">

I'm hacking on my own self driving car and trying to enhance lat control:
https://github.com/commaai/openpilot/blob/devel/selfdrive/controls/lib/lateral_mpc/generator.cpp#L111

**Comment by lee-ck** [comment]
ocp.subjectTo( -0.4363*index <= del_steer <= 0.4363*index );
ocp.subjectTo( -3*index <= del_acceleration   <= 3*index );

these are constraints of that

**Comment by zorrobyte** [comment]
Thank you. So it seems if I were to:
Control t;
....
index = 1;
ocp.subjectTo( -0.4363*index <= t <= 0.4363*index );

It would constrain the degrees/sec to -3/3?

https://github.com/commaai/openpilot/blob/devel/selfdrive/controls/lib/lateral_mpc/generator.cpp#L111

Or are these just all hard constraints, boundaries? I don't quite understand how Acado does deg/sec constraint when the syntax is the same. https://github.com/lee-ck/Model-Predictive-Control/blob/master/MPC_carmodel/ACADO/ACADO_main_.m#L107 is it because the subjectto is referencing the Control and not the DifferentialState?

EDIT:
Or, this this not a code comment? -- % input rate (-> per sec)
Control del_steer del_acceleration; % input rate (-> per sec)

**Comment by lee-ck** [comment]
Yes.
In your case, t means delta/sec . 
 `ocp.subjectTo( deg2rad(-3) <= t<= deg2rad(3)); `
It would constrain the degrees/sec to -3/3 .

**Comment by zorrobyte** [comment]
Thank you kindly Lee. Please enjoy your weekend!
![image](https://user-images.githubusercontent.com/7257172/64469867-b4372580-d107-11e9-994b-a945f3814145.png)

**Comment by zorrobyte** [comment]
It works!!

<img width="1680" alt="image" src="https://user-images.githubusercontent.com/7257172/64470515-27de3000-d112-11e9-99b8-c09f3968e668.png">

**Comment by lee-ck** [comment]
Goood!!
