### ISSUE TITLE
CPP version?

### ISSUE THREAD

**Issue by hhxzzy** [lee-ck/Model-Predictive-Control#2]
Hello! Is that a CPP version of this code?
Thanks a lot!

**Comment by lee-ck** [comment]
If you run ACADO_main_.m file, you can find CPP files which generated by ACADO toolkit. 
Check this website http://acado.github.io/ for details.

**Comment by hhxzzy** [comment]
Thank you very much for your reply!
I am new to ACADO. Some of my questions may be naive. I can run your code on matlab and I think the result is excellent. Now I am trying to write a code with similar effect on Linux and without matlab. But I am not very clear about what to do first. Do you have any examples of MPC path tracking using ACADO with only CPP? 
I also find the CPP files generated by ACADO after running ACADO_main_.m. But I have no idea how to use them.
Can you give me some adivse? Any reply will be appreciated!
Thanks!

**Comment by lee-ck** [comment]
Sorry I have an example, but it's hard to share. However, there is a good example on the ACADO website, so please refer to it.

http://acado.sourceforge.net/doc/html/db/daf/cgt_getting_started.html

You write code in the same way as in MATLAB.

**Comment by hhxzzy** [comment]
I will try this. Thank you so much.
